# Generated by Django 3.2 on 2022-09-01 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Taskname', models.CharField(max_length=30)),
                ('Priority', models.IntegerField(unique=True)),
                ('Date', models.IntegerField(unique=True)),
            ],
        ),
    ]
