# Generated by Django 3.2 on 2022-09-02 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app18', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='Date',
            field=models.DateField(),
        ),
    ]
